---
title: "Presentazione Covid19"
author: "Rodolfo Pedace"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lubridate)
library(plotly)
library(tidyverse)
```

```{r}
covid = read.csv(file = 'csv/seconddataset.csv')

#Sostituisco il valore di string a date
head(covid)
dim(covid)
covid$Date = ymd(covid$Date)
head(covid)

#Mettono in ordine crescente le date
covid = arrange(covid, Date)
tail(covid)

```

```{r}
dw = read.csv(file = 'csv/firstdataset.csv')
head(dw)
dw$Date = ymd(dw$Date)
dw = arrange(dw, Date)
head(dw)

#casi confermati
cnf = '#0066FF'
#casi di morte
dth = '#c00000'
#casi di guarigione
rec = '#00FF66'

fg = plot_ly(dw, x = ~Date)

cnf.l = list(color = cnf, width = 3)
dth.l = list(color = dth, width = 3)
rec.l = list(color = rec, width = 3)

fg = fg %>% add_trace(y = ~Confirmed, name = 'Confermati', mode = 'lines', type ='scatter', line = cnf.l)
fg = fg %>% add_trace(y = ~Recovered, name = 'Guariti', mode = 'lines', type ='scatter', line = rec.l)
fg = fg %>% add_trace(y = ~Deaths, name = 'Morti', mode = 'lines', type ='scatter', line = dth.l)

fg = fg %>% layout(title = ' Casi totali nel mondo di Covid19',
                   xaxis = list(title = 'Tempo'),
                   yaxis = list(title = ' Casi Totali'))
fg
```

```{r}
head(covid)

tail(covid)

latest = covid %>% filter(Date == max(Date)) %>% arrange(desc(Confirmed))

top10 = latest %>% slice(1:10)

top10

summary(top10)

top10$Country = factor(top10$Country, levels = c(as.character(top10$Country)))

values = as.character(top10$Confirmed) 

ly1 = plot_ly(top10, x = ~Country, y = ~Confirmed, type = 'bar', name = 'Casi Confermati', text = values, textposition = 'auto', marker = list(color = heat.colors(n=10)))

ly1 = ly1 %>% layout(title = 'Top 10 Nazioni con pi첫 casi confermati di Covid19',
                   xaxis = list(title = 'Nazioni'),
                   yaxis = list(title = ' Casi Confermati'))
ly1

```

```{r}
fg1 = plot_ly(dw, x = ~Date, y = ~New.Cases, type = 'bar', name = 'Nuovi Casi')
fg2 = plot_ly(dw, x = ~Date, y = ~Deaths...100.Cases, type = 'bar', name = 'Morti / 100 Casi')
fg3 = plot_ly(dw, x = ~Date, y = ~Recovered...100.Cases, type = 'bar', name = 'Guariti / 100 Casi')

subplot(fg1, fg2, fg3, nrows = 3, shareX = FALSE)
```

```{r}
ly2 = plot_ly(data = top10, x = ~Confirmed, y = ~Deaths, type = 'scatter', text = values, mode = 'markers', color = ~Country,
       colors = heat.colors(n=10), size = ~Confirmed, marker = list(size = ~1e-4*Deaths))

ly2 = ly2 %>% layout(title = 'Top 10 Nazioni con pi첫 morti su casi confermati di Covid19',
                   xaxis = list(title = 'Casi Confermati'),
                   yaxis = list(title = 'Morti'))
ly2
```

```{r}
#Italia Analisi
it = covid %>% filter(Country== 'Italy') %>% arrange(Date)

fg1 = plot_ly(it, x = ~Date, y = ~Confirmed, type = 'scatter', mode = 'lines', name = 'Casi Confermati')
fg2 = plot_ly(it, x = ~Date, y = ~Recovered, type = 'scatter', mode = 'lines', name = 'Casi Guariti')
fg3 = plot_ly(it, x = ~Date, y = ~Deaths, type = 'scatter', mode = 'lines', name = 'Casi Morti')

subplot(fg1, fg2, fg3, nrows = 3, shareX = FALSE)

italy = read.csv(file = 'csv/itadataset.csv')
head(italy)

ly3 = plot_ly(italy, x = ~TotalHospitalizedPatients, y = ~IntensiveCarePatients, type = 'scatter', mode = 'lines')

ly3 = ly3 %>% layout(title = 'Rapporto tra i pazienti totali in ospedale e i casi in terapia intensiva',
                   xaxis = list(title = 'Tot Pazienti ospedale'),
                   yaxis = list(title = 'Pazienti in terapia intensiva'))
ly3
```

```{r}
l2 = italy %>% filter(Date == max(Date)) %>% arrange(desc(Recovered))

reg10 = l2 %>% slice(1:10)

reg10$RegionName = factor(reg10$RegionName, levels = c(as.character(reg10$RegionName)))

v2 = as.character(reg10$Recovered) 

ly4 = plot_ly(reg10, x = ~RegionName, y = ~Recovered, type = 'bar', text = v2, textposition = 'auto', marker = list(color='orange'))
ly4 = ly4 %>% layout(title = 'Top 10 Regioni Italiane con pi첫 casi guariti',
                   xaxis = list(title = 'Regioni'),
                   yaxis = list(title = 'Guariti'))
ly4
```

```{r}
l1 = italy %>% filter(Date == max(Date)) %>% arrange(desc(Deaths))

reg10 = l1 %>% slice(1:10)

reg10$RegionName = factor(reg10$RegionName, levels = c(as.character(reg10$RegionName)))

v = as.character(reg10$Deaths) 

ly4 = plot_ly(reg10, x = ~RegionName, y = ~Deaths, type = 'bar', text = v, textposition = 'auto', marker = list(color='orange'))
ly4 = ly4 %>% layout(title = 'Top 10 Regioni Italiane con pi첫 morti',
                   xaxis = list(title = 'Regioni'),
                   yaxis = list(title = 'Morti'))
ly4
```